### ISSUE TITLE
Post failedTypeError: Failed to fetch

### ISSUE THREAD

**Issue by fernandom241** [Amiron49/Aris.Moe.Ocr.Translation.Overlay#49]
Yesterday it was still fine and working as intended but now everytime i tried to translate images it says "Post failedTypeError: Failed to fetch". Hope you can update and fix this problem because there is no other extension in google chrome that actually can translate from RAW novels site.

**Comment by Amiron49** [comment]
I looked into it and the problem is that I reached my cost control limit for DeepL for this month (65,00 € for 3.250.070 characters) which basically causes my Server to return errors. The limit will resets roughly on 17th of each month so you'd have to wait for that
